MeslekOdalariWebUI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeslekOdalariWebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MeslekOdalariWebUI/Controllers/SendMessageController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.MessageDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;

namespace MeslekOdalariWebUI.Controllers
{
    public class SendMessageController : Controller
    {
        private readonly IMessageService _messageService;
        private readonly IMapper _mapper;

        public SendMessageController(IMapper mapper, IMessageService messageService)
        {
            _mapper = mapper;
            _messageService = messageService;
        }

        [HttpPost]
        public async Task< IActionResult> SendMessage(CreateMessageDto createMessageDto)
        {
            var newMessage = _mapper.Map<Message>(createMessageDto);
            await _messageService.TCreateAsync(newMessage);
            return RedirectToAction("Index","Default");
        }
    }
}

MeslekOdalariWebUI/Views/Shared/Components/_DefaultMessage/Default.cshtml
<div class="col-lg-5">
    <form asp-controller="SendMessage" asp-action="SendMessage"  method="post" id="contact-form">
        <div class="row">
            <div class="col-lg-12">
                <fieldset>
                    <label for="name">Ad Soyad</label>
                    <input type="name" name="Name" id="name" placeholder="Adınız Soyadınız..."  required>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="email">Email</label>
                    <input type="text" name="Email" id="email" placeholder="E-mail Adresiniz..." required="">
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="subject">Konu</label>
                    <input type="subject" name="Subject" id="subject" placeholder="Konu..." autocomplete="on">
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <label for="message">Mesaj</label>
                    <textarea name="MessageContent" id="message" placeholder="Mesajınızı Buraya Yazabilirsiniz.."></textarea>
                </fieldset>
            </div>
            <div class="col-lg-12">
                <fieldset>
                    <button type="submit" id="form-submit" class="orange-button">Gönder</button>
                </fieldset>
            </div>
        </div>
    </form>
</div>