MeslekOdalariWebUI/Controllers/BannerController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.BannerDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class BannerController : Controller
    {
        private readonly IBannerService _bannerService;
        private readonly IMapper _mapper;

        public BannerController(IBannerService bannerService, IMapper mapper)
        {
            _bannerService = bannerService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _bannerService.TGetListAsync();
            var bannerList = _mapper.Map<List<ResultBannerDto>>(values);
            return View(bannerList);
        }
         public async Task<IActionResult>DeleteBanner(ObjectId id)
        {
            await _bannerService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }
        public IActionResult CreateBanner()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult>CreateBanner(CreateBannerDto createBannerDto)
        {
            var newBanner = _mapper.Map<Banner>(createBannerDto);
            await _bannerService.TCreateAsync(newBanner);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult>UpdateBanner(ObjectId id)
        {
            var value = await _bannerService.TGetByIdAsync(id);
            var updateBanner = _mapper.Map<UpdateBannerDto>(value);
            return View(updateBanner);
        }
        [HttpPost]
        public async Task<IActionResult>UpdateBanner(UpdateBannerDto updateBannerDto)
        {
            var banner = _mapper.Map<Banner>(updateBannerDto);
            await _bannerService.TUpdateAsync(banner);
            return RedirectToAction("Index");
        }



    }
}

MeslekOdalariWebUI/Controllers/DefaultController.cs
using Microsoft.AspNetCore.Mvc;

namespace MeslekOdalariWebUI.Controllers
{
    public class DefaultController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

MeslekOdalariWebUI/Controllers/NewsController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.NewsDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsService _newsService;
        private readonly IMapper _mapper;

        public NewsController(IMapper mapper, INewsService newsService)
        {
            _mapper = mapper;
            _newsService = newsService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _newsService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultNewsDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteNews(ObjectId id)
        {
            await _newsService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateNews()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateNews(CreateNewsDto createNewsDto)
        {
            var newValue = _mapper.Map<News>(createNewsDto);
            await _newsService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateNews(ObjectId id)
        {
            var value = await _newsService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateNewsDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateNews(UpdateNewsDto updateNewsDto)
        {
            var updateValue = _mapper.Map<News>(updateNewsDto);
            await _newsService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Controllers/RoomsController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.NewsDtos;
using MeslekOdalari.Dto.Dtos.RoomsDto;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class RoomsController : Controller
    {
        private readonly IRoomsService _roomsService;
        private readonly IMapper _mapper;

        public RoomsController(IMapper mapper, IRoomsService roomsService)
        {
            _mapper = mapper;
            _roomsService = roomsService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _roomsService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultRoomsDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteRooms(ObjectId id)
        {
            await _roomsService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateRooms()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateRooms(CreateRoomsDto createRoomsDto)
        {
            var newValue = _mapper.Map<Rooms>(createRoomsDto);
            await _roomsService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateRooms(ObjectId id)
        {
            var value = await _roomsService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateRoomsDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateRooms(UpdateRoomsDto updateRoomsDto)
        {
            var updateValue = _mapper.Map<Rooms>(updateRoomsDto);
            await _roomsService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
        public async Task<IActionResult> RoomsDetails(ObjectId id)
        {
            var value = await _roomsService.TGetByIdAsync(id);
            var rooms = _mapper.Map<ResultRoomsDto>(value);
            return View(rooms);
        }
    }
}

MeslekOdalariWebUI/Controllers/VideoController.cs
using AutoMapper;
using MeslekOdalari.Business.Abstract;
using MeslekOdalari.Dto.Dtos.NewsDtos;
using MeslekOdalari.Dto.Dtos.VideoDtos;
using MeslekOdalari.Entity.Entities;
using Microsoft.AspNetCore.Mvc;
using MongoDB.Bson;

namespace MeslekOdalariWebUI.Controllers
{
    public class VideoController : Controller
    {
        private readonly IVideoService _videoService;
        private readonly IMapper _mapper;

        public VideoController(IMapper mapper, IVideoService videoService)
        {
            _mapper = mapper;
            _videoService = videoService;
        }

        public async Task<IActionResult> Index()
        {
            var values = await _videoService.TGetListAsync();
            var valueList = _mapper.Map<List<ResultVideoDto>>(values);
            return View(valueList);
        }
        public async Task<IActionResult> DeleteVideo(ObjectId id)
        {
            await _videoService.TDeleteAsync(id);
            return RedirectToAction("Index");
        }

        public IActionResult CreateVideo()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CreateVideo(CreateVideoDto createVideoDto)
        {
            var newValue = _mapper.Map<Video>(createVideoDto);
            await _videoService.TCreateAsync(newValue);
            return RedirectToAction("Index");
        }
        public async Task<IActionResult> UpdateVideo(ObjectId id)
        {
            var value = await _videoService.TGetByIdAsync(id);
            var updateValue = _mapper.Map<UpdateVideoDto>(value);
            return View(updateValue);
        }
        [HttpPost]
        public async Task<IActionResult> UpdateVideo(UpdateVideoDto updateVideoDto)
        {
            var updateValue = _mapper.Map<Video>(updateVideoDto);
            await _videoService.TUpdateAsync(updateValue);
            return RedirectToAction("Index");

        }
    }
}

MeslekOdalariWebUI/Views/Shared/Components/_AdminSidebar/Default.cshtml
<div class="quixnav">
    <div class="quixnav-scroll">
        <ul class="metismenu" id="menu">
            <li class="nav-label first">Admin Paneli</li>

            <li>
                <a asp-controller="Banner" asp-action="Index">
                    <i class="fa fa-image"></i>
                    <span class="nav-text">Banner</span>
                </a>
            </li>

            <li>
                <a asp-controller="Contact" asp-action="Index">
                    <i class="fa fa-envelope"></i>
                    <span class="nav-text">İletişim Bilgisi</span>
                </a>
            </li>

            <li>
                <a asp-controller="Counter" asp-action="Index">
                    <i class="fa fa-calculator"></i>
                    <span class="nav-text">Sayaç</span>
                </a>
            </li>

            <li>
                <a asp-controller="Feature" asp-action="Index">
                    <i class="fa fa-list"></i>
                    <span class="nav-text">Öne Çıkanlar</span>
                </a>
            </li>

            <li>
                <a asp-controller="Project" asp-action="Index">
                    <i class="fa fa-folder "></i>
                    <span class="nav-text">Projeler</span>
                </a>
            </li>

            <li>
                <a asp-controller="Regulation" asp-action="Index">
                    <i class="fa fa-gavel"></i>
                    <span class="nav-text">Mevzuat</span>
                </a>
            </li>

            <li>
                <a asp-controller="Message" asp-action="Index">
                    <i class="fa fa-comment"></i>
                    <span class="nav-text">Gelen Mesajlar</span>
                </a>
            </li>

            <li>
                <a asp-controller="News" asp-action="Index">
                    <i class="fa fa-tag"></i>
                    <span class="nav-text">Haberler</span>
                </a>
            </li>

            <li>
                <a asp-controller="Rooms" asp-action="Index">
                    <i class="fa fa-building"></i>
                    <span class="nav-text">Meslek Odaları</span>
                </a>
            </li>

            <li>
                <a asp-controller="Question" asp-action="Index">
                    <i class="fa fa-question"></i>
                    <span class="nav-text">Sorular-Cevaplar</span>
                </a>
            </li>

            <li>
                <a asp-controller="SubHeader" asp-action="Index">
                    <i class="fa fa-info-circle"></i>
                    <span class="nav-text">Üst Bilgi</span>
                </a>
            </li>

            <li>
                <a asp-controller="Video" asp-action="Index">
                    <i class="fa fa-play"></i>
                    <span class="nav-text">Video</span>
                </a>
            </li>

            <li>
                <a asp-controller="Default" asp-action="Index">
                    <i class="fa fa-laptop"></i>
                    <span class="nav-text">Siteye Git</span>
                </a>
            </li>
        </ul>
    </div>
</div>

<style>
    .quixnav {
        background-color: #2c3e50;
        width: 275px;
        padding-top: 20px;
        padding-bottom: 20px;
        border-radius: 0px;
    }

    .quixnav-scroll {
        overflow-y: auto;
        max-height: 90vh;
        padding: 0 10px;
    }

    .metismenu {
        list-style: none;
        padding: 0;
        margin: 0;
    }

        .metismenu li {
            margin-bottom: 15px;
        }

        .metismenu a {
            display: flex;
            align-items: center;
            text-decoration: none;
            color: #ecf0f1;
            font-size: 20px; /* Yazı büyütüldü */
            font-weight: 500;
            padding: 10px 15px;
            border-radius: 8px;
            transition: background-color 0.3s, transform 0.3s;
        }

            .metismenu a:hover {
                background-color: #34495e;
                transform: translateX(5px);
            }

        .metismenu i {
            margin-right: 10px;
            font-size: 24px; /* İkon da biraz büyütüldü */
        }

    .nav-label {
        font-size: 20px; /* Admin Paneli yazısı büyüklüğü korunuyor */
        font-weight: bold;
        color: #bdc3c7;
        margin-bottom: 20px;
        padding-left: 15px;
    }

</style>